# Generated by Django 5.0.1 on 2024-09-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cod_produto', models.CharField(blank=True, max_length=8, null=True)),
                ('lote', models.CharField(blank=True, max_length=10, null=True)),
                ('quantidade', models.IntegerField()),
                ('status', models.BooleanField()),
                ('data', models.DateField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
