# Generated by Django 5.0.1 on 2024-10-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'permissions': [('ver_estoque_por_lotes', 'Can see stock by batches'), ('ver_necessidade_pedidos', 'Can see the need for orders')]},
        ),
    ]
