# Generated by Django 5.0.1 on 2024-12-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_inventariosestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosestoque',
            name='conferente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
