# Generated by Django 5.0.1 on 2024-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_inventariosestoque_conferente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosestoque',
            name='numero_inventario',
            field=models.IntegerField(default=0),
        ),
    ]
