# Generated by Django 5.0.1 on 2024-12-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_alter_inventariosestoque_numero_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariosestoque',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
