# Generated by Django 5.0.1 on 2024-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_inventariosestoque_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosestoque',
            name='nome_produtos',
            field=models.CharField(default='nada', max_length=60),
        ),
    ]
