# Generated by Django 5.0.1 on 2025-01-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_inventariosestoque_nome_produtos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariosestoque',
            options={'permissions': [('ver_inventario_estoque', 'Can see stock inventory'), ('editar_inventario_estoque', 'Can edit stock inventory')]},
        ),
    ]
