# Generated by Django 5.0.1 on 2025-01-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_inventariosestoque_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='inventario',
            field=models.BooleanField(default=False),
        ),
    ]
