# Generated by Django 5.0.1 on 2025-01-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_alter_estoque_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosestoque',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
