# Generated by Django 5.0.1 on 2025-01-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_inventariosestoque_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='id_inventario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
