# Generated by Django 5.0.1 on 2024-07-03 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cnpj', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('product_code', models.CharField(blank=True, max_length=10, null=True)),
                ('product_bar_code', models.IntegerField(blank=True, null=True)),
                ('box_bar_code', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('fabricado', 'Fabricado'), ('kit', 'Kit'), ('kit_variavel', 'Kit Variável'), ('materia_prima', 'Matéria Prima')], max_length=15)),
                ('unit', models.CharField(max_length=10)),
                ('box_quantity', models.IntegerField(blank=True, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ncm', models.IntegerField(blank=True, null=True)),
                ('cest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cpf', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Materiais_de_Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('unit', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=25)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.fornecedores')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('regime', models.CharField(choices=[('simples', 'Simples'), ('normal', 'Normal')], max_length=10)),
                ('cnpj', models.IntegerField()),
                ('ie', models.IntegerField()),
                ('cep', models.IntegerField()),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('nota_fiscal', models.CharField(choices=[('nota cheia', 'Nota Cheia'), ('meia nota', 'Meia Nota'), ('1/3 nota', '1/3 Nota'), ('70% valor 70% quantidade', '70% Valor 70% Quantidade')], max_length=24)),
                ('Gerente_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerente_comercial', to='cadastros.vendedores')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedor', to='cadastros.vendedores')),
                ('vendedor_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedor_adjunto', to='cadastros.vendedores')),
            ],
        ),
    ]
