# Generated by Django 5.0.1 on 2024-07-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_vendedores_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('valor_sem_impostos', models.DecimalField(decimal_places=2, max_digits=3)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.products')),
            ],
        ),
    ]
