# Generated by Django 5.0.1 on 2024-07-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelapreco',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tabelapreco',
            name='valor_sem_impostos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
