# Generated by Django 5.0.1 on 2024-07-07 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_tabelapreco_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelapreco',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='tabelapreco',
            name='valor_sem_impostos',
        ),
        migrations.CreateModel(
            name='TabelaPrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_sem_impostos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.products')),
                ('tabela_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.tabelapreco')),
            ],
        ),
    ]
