# Generated by Django 5.0.1 on 2024-07-13 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_tabelaprecoproduto_comissao_gerente_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='TabelaPreco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tabelapreco'),
        ),
    ]
