# Generated by Django 5.0.1 on 2024-07-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_clientes_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='TabelaPreco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tabelapreco'),
        ),
    ]
