# Generated by Django 5.0.1 on 2024-07-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_clientes_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='TabelaPreco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.tabelapreco'),
        ),
    ]
