# Generated by Django 5.0.1 on 2024-07-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_clientes_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='box_bar_code',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='cest',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='products',
            name='ncm',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_bar_code',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
