# Generated by Django 5.0.1 on 2024-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_clientes_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='estoq_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
