# Generated by Django 5.0.1 on 2025-01-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_products_estoq_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.products')),
                ('produto_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_kit', to='cadastros.products')),
            ],
        ),
    ]
