# Generated by Django 5.0.1 on 2024-08-09 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_pedido_aprovado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoSeparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separacoes', to='vendas.pedidoitem')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separacoes', to='vendas.pedido')),
            ],
        ),
    ]
