# Generated by Django 5.0.1 on 2024-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_pedidoitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
