# Generated by Django 5.0.1 on 2024-09-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_pedido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(default=2),
        ),
    ]
