# Generated by Django 5.0.1 on 2024-09-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='finalizado',
        ),
    ]
