# Generated by Django 5.0.1 on 2024-10-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_remove_pedido_aprovado_remove_pedido_finalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': [('alterar_status', 'can chance status')]},
        ),
    ]
