# Generated by Django 5.0.1 on 2024-10-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_pedidoseparacao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaltandoSeparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=20)),
                ('quantidade_pedido', models.PositiveIntegerField()),
                ('quantidade_separada', models.PositiveIntegerField()),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltando_separacao', to='vendas.pedidoitem')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltando_separacao', to='vendas.pedido')),
            ],
        ),
    ]
