# Generated by Django 5.0.1 on 2024-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_pedido_usuario_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('em_aberto', 'Em Aberto'), ('aprovados', 'Aprovados'), ('separando', 'Separando'), ('conf_separacao', 'Conferência Separação'), ('separacao_finalizada', 'Separação Finalizada'), ('finalizados', 'Finalizados'), ('cancelado', 'Cancelado')], default='em_aberto', max_length=20),
        ),
    ]
