# Generated by Django 5.0.1 on 2025-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_finalizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
