# Generated by Django 5.0.1 on 2025-01-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_pedido_data_finalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportadora', models.CharField(max_length=255)),
                ('data_saida', models.DateField()),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido')),
            ],
        ),
    ]
