# Generated by Django 5.0.1 on 2025-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0016_saidapedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidapedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
