# Generated by Django 5.0.1 on 2025-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_alter_pedido_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='regime_venda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
