# Generated by Django 5.0.1 on 2025-01-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0019_pedido_regime_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_finalizado',
        ),
    ]
