# Generated by Django 5.0.1 on 2025-01-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0020_remove_pedido_data_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade_inicial_caixas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
