# Generated by Django 5.0.1 on 2024-07-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0002_transferenciaestoquesaidaprodutos_codigo_barra_caixa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaestoquesaidaprodutos',
            name='codigo_barra_caixa',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='transferenciaestoquesaidaprodutos',
            name='codigo_barra_unidade',
            field=models.CharField(max_length=13),
        ),
    ]
