# Generated by Django 5.0.1 on 2024-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0003_alter_transferenciaestoquesaidaprodutos_codigo_barra_caixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaestoquesaidainfo',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
