# Generated by Django 5.0.1 on 2024-08-05 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_alter_products_category'),
        ('produtos_acabados', '0004_transferenciaestoquesaidainfo_validado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=20)),
                ('quantidade_unitaria', models.IntegerField()),
                ('produto_misto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misto_items', to='cadastros.products')),
                ('produto_misto_another', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misto_items', to='cadastros.products_another_info')),
            ],
        ),
        migrations.CreateModel(
            name='MistoComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misto_components', to='cadastros.products')),
                ('produto_another', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='misto_components', to='cadastros.products_another_info')),
                ('misto_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='produtos_acabados.mistoitem')),
            ],
        ),
    ]
