# Generated by Django 5.0.1 on 2024-08-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0005_mistoitem_mistocomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mistoitem',
            name='produto_misto',
        ),
        migrations.RemoveField(
            model_name='mistoitem',
            name='produto_misto_another',
        ),
        migrations.DeleteModel(
            name='MistoComponent',
        ),
        migrations.DeleteModel(
            name='MistoItem',
        ),
    ]
