# Generated by Django 5.0.1 on 2024-08-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('produtos_acabados', '0006_remove_mistoitem_produto_misto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MistoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=20)),
                ('quantidade_unitaria', models.IntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='MistoComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('lote', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('misto_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='produtos_acabados.mistoitem')),
            ],
        ),
    ]
