# Generated by Django 5.0.1 on 2024-08-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0007_mistoitem_mistocomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistoitem',
            name='produto_nome',
            field=models.CharField(default='nat', max_length=70),
        ),
    ]
