# Generated by Django 5.0.1 on 2024-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0008_mistoitem_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistoitem',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
