# Generated by Django 5.0.1 on 2024-08-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0009_mistoitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistoitem',
            name='quantidade_de_caixas',
            field=models.IntegerField(default=1),
        ),
    ]
