# Generated by Django 5.0.1 on 2024-08-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0011_alter_mistoitem_quantidade_de_caixas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistoitem',
            name='quantidade_de_caixas',
            field=models.IntegerField(default=1),
        ),
    ]
