# Generated by Django 5.0.1 on 2024-10-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0012_alter_mistoitem_quantidade_de_caixas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciaestoquesaidainfo',
            options={'permissions': [('listar_trans_para_conferencia', 'Can List Transfs to Confer'), ('validar_transferencias', 'Can Validate Transfers')]},
        ),
    ]
