# Generated by Django 5.0.1 on 2024-10-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos_acabados', '0014_alter_transferenciaestoquesaidainfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferenciaestoquesaidainfo',
            options={'permissions': [('listar_trans_para_conferencia', 'Can List Transfs to Confer'), ('validar_transferencias', 'Can Validate Transfers'), ('listar_transferencias_recebidas', 'Can List Received Transfers'), ('listar_entradas_estoque', 'Can List Stock Entries'), ('is_admin_transfer', 'Can skip barcode and date validation for transfers')]},
        ),
    ]
